name: d_event_bus
description: A simple, flexible, and powerful event bus implementation for Dart, designed for decoupling different parts of an application in a clean, type-safe way.
version: 1.0.0
repository: https://github.com/dipflix/event_bus

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
